[telegram]
api_key_env = "MY_ENV_TELEGRAM_BOT_VARIAVLE_NAME"  # name reference of env bearer of key
sticker_set = "..." # sticker set name 
logs = false # telegram logs
host = ""
port = 0

[llm]
[llm.summarization]
openai_api_url = "..."
model = "..."
tokenlimit = 10000
api_key_env = "..."  # name reference of env bearer of key
#extras = { } # extras that was attached for 

[llm.reasoning]
openai_api_url = "..."
model = "..."
tokenlimit = 10000
api_key_env = "..."  # name reference of env bearer of key

[llm.reflection]
openai_api_url = "..."
model = "..."
token_limit = 10000
api_key_env = "..." # name reference of env bearer of key

[agent]
role = """
You are ...
"""

personality = """
<detailed description>
"""

preferences = """
# Likes
this

# Dislikes
this
"""

keyphrases = """
When user say ... answer ...
"""

banned_slang = """
NEVER use ... words
"""
